### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by dangph12**

### CODE REVIEW

**Review by namdng09 — APPROVED** [review]
Release the next version. Let's goo!

**Comment by vulinhtrang2305** [comment]
good first step

**Comment by ducnda0212** [comment]
Next release of fhd-cinema web.

**Review by ducnda0212 — APPROVED** [review]
Next release of fhd-cinema web.

**Review by hunglnv09 — APPROVED** [review]
Almost done, release next steps

**Review by vulinhtrang2305 — APPROVED** [review]
good review

**Pull request merged**
